SELECT TOP 50000 * FROM POSTS WHERE POSTS.VIEWCOUNT <= (SELECT MAX(Posts.ViewCount) FROM Posts) ORDER BY POSTS.VIEWCOUNT DESC

SELECT TOP 50000 * FROM POSTS WHERE POSTS.VIEWCOUNT<= 127402 ORDER BY POSTS.VIEWCOUNT DESC;

SELECT TOP 50000 * FROM POSTS WHERE POSTS.VIEWCOUNT<= 74596 ORDER BY POSTS.VIEWCOUNT DESC;

SELECT TOP 50000 * FROM POSTS WHERE POSTS.VIEWCOUNT<= 53211 ORDER BY POSTS.VIEWCOUNT DESC;
